global:
  scrape_interval: 15s          # Scrape after every 15 seconds
  evaluation_interval: 15s

scrape_configs:
  - job_name: "medical-chatbot"
    metrics_path: "/metrics"     # FastAPI /metrics endpoint
    static_configs:
      - targets: ["medical-fastapi:8000"]  # Scrape from FastAPI service
    scrape_interval: 10s         # Scrape more often
    honor_labels: true