apiVersion: v1
kind: Service
metadata:
  name: rag-pipeline
  namespace: model-serving
spec:
  selector:
    app: medical-chatbot
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer