apiVersion: apps/v1
kind: Deployment
metadata:
  name: medical-chatbot-deployment
  namespace: model-serving
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medical-chatbot
  template:
    metadata:
      labels:
        app: medical-chatbot
    spec:
      containers:
        - name: backend
          image: dqdung2005/medical-chatbot-rag-pipeline:v1.0.0
          resources:
            requests:
              memory: 2Gi   
              cpu: 1      
            limits:
              memory: 4Gi  
              cpu: 2       
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRES_HOST
              value: "postgres"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: "medical_chatbot"
            - name: POSTGRES_USER
              value: "admin"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: medical-chatbot-secrets
                  key: POSTGRES_PASSWORD
            - name: QDRANT_URL
              value: "http://qdrant:6333"
            - name: GROQ_API_KEY
              valueFrom:
                secretKeyRef:
                  name: medical-chatbot-secrets
                  key: GROQ_API_KEY
            - name: DEFAULT_MODEL
              value: "llama-3.1-8b-instant"
            - name: TZ
              value: "Asia/Ho_Chi_Minh"
            - name: PYTHONPATH
              value: "/app"
          volumeMounts:
            - name: model-storage
              mountPath: /app/.cache
        
        - name: frontend
          image: dqdung2005/medical-chatbot-streamlit:v1.0.0
          resources:
            requests:
              memory: 300Mi  
              cpu: 0.3      
            limits:
              memory: 500Mi 
              cpu: 0.5      
          ports:
            - containerPort: 8501
          env:
            - name: FASTAPI_URL
              value: "http://localhost:8000"

      volumes:
        - name: model-storage
          emptyDir: {}