apiVersion: v1
kind: Service
metadata:
  name: streamlit
  namespace: model-serving
spec:
  selector:
    app: medical-chatbot
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
  type: LoadBalancer 
